### ISSUE TITLE
Enhancement: client IP address

### ISSUE THREAD

**Issue by blacksqr** [jerily/twebserver#1]
This looks like a great project and I'm looking forward to trying it out.

I have a task in mind that I was going to use wapp for, but this looks like a better option. But my particular use case requires that  I have access to the IP number of the client making the connection to the server. Any chance of including that info in the request dictionary?

**Comment by blacksqr** [comment]
Ok after reading through the example code more closely, it appears the IP address is in the context dictionary passed to the route handler procedure.

**Comment by jerily** [comment]
Sorry for the late reply. I'm on a different timezone it seems. I have added ::twebserver::ipv6_to_ipv4 command to convert ipv6 addresses to ipv4 if they can be mapped (it returns empty string if they cannot be mapped - see example). Please let me know if I can help in any other way.

**Comment by blacksqr** [comment]
Thanks for your kind response.

If you have the time and inclination, I think it would also be very useful to have the option to use the SO_REUSEPORT socket option on Linux when creating a web server. Tcl has this option when a server socket is created. It would help with scaling to higher-traffic sites by allowing multiple server processes to receive client connections from a single port.

**Comment by jerily** [comment]
Thanks for the suggestion. It is now added. Please get latest. I will create a new release when I have made more changes.

**Comment by jerily** [comment]
I took the idea a step further and moved the listeners to the threads in the `event_loop_improv` branch. I have not decided whether to keep it yet but it looks like it. Thanks again.

**Comment by jerily** [comment]
SO_REUSEPORT and related refactoring works great with linux (at least on ubuntu that am currently testing) but macOS behaves differently (it uses other listeners as backup/fallback). I kept the change but need to see how to resolve issue with macOS as only one thread is utilized on macOS at the moment. It took me all day to figure out what was going on on macOS but it helped me find and resolve other issues.

If you have any suggestions on macOS, please do not hesitate and let me know.

**Comment by jerily** [comment]
This has been resolved. On macOS, main thread listens and delegates work to the threads (you can still run multiple processes on the same address/port i.e. SO_REUSEPORT is set on macOS as well). On Linux, threads are listeners via SO_REUSEPORT and process the requests they listen to.
